DELETE http://localhost:8080/events/2/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzA0NTkzMzE0LCJ1c2VySWQiOjJ9.j_W1om2_kFKpbOHkTBQqOb775fgnJdPTbOnVjWzROpU