POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzA0NTk2NDM2LCJ1c2VySWQiOjJ9.DDRsbMcZxxWwGZk3Owc4uy6K9rDLoiBJ0-sZmnrgbjM

{
    "title": "Event 2",
    "description": "Event 2 description",
    "location": "Event 2 location",
    "DateTime": "2024-02-02T15:35:00.000Z"
}