DELETE http://localhost:8080/events/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxQGV4YW1wbGUuY29tIiwiZXhwIjoxNzA0NTY0MzE3LCJ1c2VySWQiOjF9.LqT6osDJwnm5HheKWCMwtDj7wa4yPPdykfmUEgA0MpM