PUT http://localhost:8080/events/3
content-type: application/json

{
    "title": "TRES",
    "description": "Event 3 description",
    "location": "Event 3 location",
    "DateTime": "2024-06-01T15:35:00.000Z"
}